version: 2
jobs:
  build:
    working_directory: ~/kasi
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run "python test/run.py"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
          
