version: 2
jobs:
  build_and_test:
    working_directory: ~/kasi
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job

    steps:
      - checkout
      - run: mkdir test-reports
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            sudo pip install --upgrade pip
            pipenv install
      - run: 
          command | 
            pipenv run "pip install -r requirements-dev.txt"
      - run:
#          command: pipenv run "python test/run.py"
          command: pipenv run "python demo/start.py"

      - store_test_results:
          path: test-results
#      - store_artifacts:
#          path: test-results
#          destination: tr1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master
          
